name: Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # The gcc version from ubuntu-latest segfaults when trying to compile my beautiful code
      CC: gcc-13 
    steps:
    - uses: actions/checkout@v4
    - name: Install Tools
      run: sudo apt update && sudo apt install -y valgrind $CC
    - name: make test
      run: make test
    - name: make valgrind
      run: make valgrind
